name: Sync Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to destination repository
        env:
          TOKEN: ${{ secrets.DESTINATION_TOKEN }}
        run: |
          git remote add mirror https://x-access-token:${TOKEN}@github.com/ishuD26/sync-demo-destination.git
          git push --mirror mirror
