name: Sync Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git remote add mirror https://github.com/ishuD26/sync-demo-destination.git
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ishuD26/sync-demo-destination.git --all
