name: Sync Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug secret exists
        run: |
          if [ -z "${{ secrets.DESTINATION_TOKEN }}" ]; then
            echo "SECRET NOT FOUND"
            exit 1
          else
            echo "SECRET FOUND"
          fi

      - name: Push to destination repository
        env:
          TOKEN: ${{ secrets.DESTINATION_TOKEN }}
        run: |
          git remote add mirror https://x-access-token:${TOKEN}@github.com/ishuD26/sync-demo-destination.git
          git push --mirror mirror
